version: "3.9"
services:
  web:
    depends_on:
      - database
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
    environment:
        - DATABASE_URL=postgresql://user:password@database:5432/gametracker
    ports:
      - "8080:8080"

  database:
    image: postgres:13
    environment:
      POSTGRES_DB: gametracker
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  data:
