FROM golang:1.22

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

RUN go install github.com/go-delve/delve/cmd/dlv@latest

COPY . .

RUN go build -gcflags="all=-N -l" -o /go/bin/app

EXPOSE 8080 40000

CMD ["dlv", "debug", "--headless", "--listen=:40000", "--api-version=2", "--accept-multiclient", "--log"]