version: "3.9"
services:
  database:
    image: postgres:13
    container_name: database
    environment:
      POSTGRES_DB: gametracker
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    container_name: backend
    depends_on:
      - database
    build:
      dockerfile: Dockerfile
      context: .
    environment:
        - DATABASE_URL=postgresql://user:password@database:5432/gametracker
    ports:
      - "8080:8080"
    links:
      - database



volumes:
  data:
