FROM golang:1.22

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

# Build Delve
RUN go install github.com/go-delve/delve/cmd/dlv@latest

RUN go build -o /go/bin/app

expose 8080

CMD ["dlv", "debug", "--headless=true", "--listen=:2345", "--api-version=2", "--log"]