name: Check code

on:
  pull_request:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
            with:
              fetch-depth: 0

          - name: Set up Go
            uses: actions/setup-go@v2

          - name: Build
            run: go build -o ./bin/backend ./main.go

          - name: Build Docker image
            run: docker build -t backend .

          - name: Push Dokku image
            uses: idoberko2/dokku-deploy-github-action@v1
            with:
              ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
              dokku-host: server.erudev.page
              app-name: gametracker-backend
              remote-branch: main