name: Check and Deploy to Production

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Build
        run: go build -o ./bin/backend ./main.go

      - name: Build Docker image
        run: docker build -t backend .